# Generated by Django 4.2.11 on 2025-04-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0002_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='Sem telefone', max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=15),
        ),
    ]
