# Generated by Django 4.2.11 on 2025-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0002_jogo_categoria_alter_jogo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(upload_to='jogos/'),
        ),
    ]
