# Generated by Django 4.2.11 on 2025-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0003_alter_jogo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
