# Generated by Django 4.2.11 on 2025-06-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0004_jogo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='jogo',
            name='categorias',
            field=models.ManyToManyField(to='cadastro_jogos.categoria'),
        ),
    ]
