# Generated by Django 4.2.11 on 2025-06-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0005_categoria_remove_jogo_categoria_jogo_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='categorias',
        ),
        migrations.AddField(
            model_name='jogo',
            name='categoria',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
